### ISSUE TITLE
Starting errors

### ISSUE THREAD

**Issue by nzfarmer1** [janoglezcampos/GstreamerChromeBridge#1]
Hi this looks great

Have tried to get it working

On the Auto Bridge am getting a pipeline syntax error for some reason

And on the initial Bridge, I get a Listen error. Am a little confused as you are attempting to listen on 8081 and also expect streamer to listen on the same port?

**Comment by janoglezcampos** [comment]
Hello! 
Sorry for answering a llitle bit late :/

Are you being able to run gstreamer on the command line?
(gst-launch-1.0 gst-launch-1.0 videotestsrc ! video/x-raw, framerate=30/1, width=320, height=240 ! videoconvert ! queue ! theoraenc ! queue ! m. oggmux name=m ! queue ! tcpserversink host=localhost port=8081)

If you do, can you attach the error given by the script pls

We create the TCP server with nodejs, so we listen to incoming connections from clients, and then gstreamer connects as  a client to the server on that same port, and nodjs it redirects it to the httpserver.

Can you also attach the the error on the second script?
